#pragma checksum "D:\Dropbox\University of Washington\Winter 2013\CSS490\AnimalMath\AnimalMath\AnimalView\MathPage.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "5F2FB7066512ABEA725CD521F1F2EAB5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Phone.Controls;
using System;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Resources;
using System.Windows.Shapes;
using System.Windows.Threading;


namespace AnimalMath {
    
    
    public partial class MathPage : Microsoft.Phone.Controls.PhoneApplicationPage {
        
        internal System.Windows.Controls.Grid LayoutRoot;
        
        internal System.Windows.Controls.Grid AnimalGrid;
        
        internal System.Windows.Controls.Image AnimalGrid_1_1;
        
        internal System.Windows.Controls.Image AnimalGrid_1_2;
        
        internal System.Windows.Controls.Image AnimalGrid_1_3;
        
        internal System.Windows.Controls.Image AnimalGrid_2_1;
        
        internal System.Windows.Controls.Image AnimalGrid_2_2;
        
        internal System.Windows.Controls.Image AnimalGrid_2_3;
        
        internal System.Windows.Controls.Image AnimalGrid_3_1;
        
        internal System.Windows.Controls.Image AnimalGrid_3_2;
        
        internal System.Windows.Controls.Image AnimalGrid_3_3;
        
        internal System.Windows.Controls.TextBlock topBarText;
        
        internal System.Windows.Controls.Button Math_Answer_0;
        
        internal System.Windows.Controls.Button Math_Answer_1;
        
        internal System.Windows.Controls.Button Math_Answer_2;
        
        internal System.Windows.Controls.Button Math_Answer_3;
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Windows.Application.LoadComponent(this, new System.Uri("/AnimalMath;component/AnimalView/MathPage.xaml", System.UriKind.Relative));
            this.LayoutRoot = ((System.Windows.Controls.Grid)(this.FindName("LayoutRoot")));
            this.AnimalGrid = ((System.Windows.Controls.Grid)(this.FindName("AnimalGrid")));
            this.AnimalGrid_1_1 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_1_1")));
            this.AnimalGrid_1_2 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_1_2")));
            this.AnimalGrid_1_3 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_1_3")));
            this.AnimalGrid_2_1 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_2_1")));
            this.AnimalGrid_2_2 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_2_2")));
            this.AnimalGrid_2_3 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_2_3")));
            this.AnimalGrid_3_1 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_3_1")));
            this.AnimalGrid_3_2 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_3_2")));
            this.AnimalGrid_3_3 = ((System.Windows.Controls.Image)(this.FindName("AnimalGrid_3_3")));
            this.topBarText = ((System.Windows.Controls.TextBlock)(this.FindName("topBarText")));
            this.Math_Answer_0 = ((System.Windows.Controls.Button)(this.FindName("Math_Answer_0")));
            this.Math_Answer_1 = ((System.Windows.Controls.Button)(this.FindName("Math_Answer_1")));
            this.Math_Answer_2 = ((System.Windows.Controls.Button)(this.FindName("Math_Answer_2")));
            this.Math_Answer_3 = ((System.Windows.Controls.Button)(this.FindName("Math_Answer_3")));
        }
    }
}

